apiVersion: v1
kind: Service
metadata:
  name: sensu-backend-service
  namespace: cloud-storage
spec:
  selector:
    app: sensu-backend
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  - name: agent
    port: 8081
    targetPort: 8081 