apiVersion: v1
kind: Service
metadata:
  name: sensu-backend-service
spec:
  selector:
    app: sensu-backend
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: websocket
      port: 8081
      targetPort: 8081 