apiVersion: v1
kind: ConfigMap
metadata:
  name: uchiwa-config
  namespace: cloud-storage
data:
  config.json: |
    {
      "sensu": [
        {
          "name": "Cloud Storage",
          "host": "sensu-backend-service.cloud-storage.svc.cluster.local",
          "port": 8080,
          "timeout": 10,
          "user": "admin",
          "pass": "P@ssw0rd"
        }
      ],
      "uchiwa": {
        "host": "0.0.0.0",
        "port": 3000,
        "refresh": 5,
        "user": "admin",
        "pass": "admin"
      }
    } 