apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cloud-storage
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'cloud-storage'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_role]
            regex: worker
            action: keep 