apiVersion: v1
kind: ConfigMap
metadata:
  name: sensu-checks
  namespace: cloud-storage
data:
  checks.yml: |
    ---
    type: CheckConfig
    api_version: core/v2
    metadata:
      name: cloud-storage-health
      namespace: default
    spec:
      command: check-http -u http://localhost:9090/metrics
      subscriptions:
        - system
      handlers:
        - slack
      interval: 30
      publish: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensu-agent
  namespace: cloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu-agent
  template:
    metadata:
      labels:
        app: sensu-agent
    spec:
      containers:
      - name: sensu-agent
        image: sensu/sensu:latest
        command: ["/opt/sensu/bin/sensu-agent"]
        args:
          - "start"
          - "--backend-url=ws://sensu-backend:8081"
          - "--subscriptions=system"
        volumeMounts:
        - name: checks
          mountPath: /etc/sensu/checks
      volumes:
      - name: checks
        configMap:
          name: sensu-checks
---
apiVersion: v1
kind: Service
metadata:
  name: sensu-agent
  namespace: cloud-storage
spec:
  selector:
    app: sensu-agent
  ports:
  - port: 3031
    targetPort: 3031
  type: NodePort 