apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensu-backend
  namespace: cloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu-backend
  template:
    metadata:
      labels:
        app: sensu-backend
    spec:
      containers:
      - name: sensu-backend
        image: sensu/sensu:latest
        command: ["/opt/sensu/bin/sensu-backend"]
        args: ["start"]
        ports:
        - containerPort: 8080
          name: dashboard
        - containerPort: 8081
          name: websocket
        - containerPort: 8082
          name: api
---
apiVersion: v1
kind: Service
metadata:
  name: sensu-backend
  namespace: cloud-storage
spec:
  selector:
    app: sensu-backend
  ports:
  - name: dashboard
    port: 3000
    targetPort: 8080
  - name: websocket
    port: 8081
    targetPort: 8081
  - name: api
    port: 8082
    targetPort: 8082
  type: NodePort 