apiVersion: apps/v1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        role: master
    spec:
      containers:
      - name: master-node
        image: nginx:alpine  # Using lightweight image for testing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 5  # This will create 5 worker nodes
  selector:
    matchLabels:
      role: worker
  template:
    metadata:
      labels:
        role: worker
    spec:
      containers:
      - name: worker-node
        image: nginx:alpine 