apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: cloud-storage
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'node-metrics'
        static_configs:
          - targets: ['localhost:8000']  # Node monitor metrics
      - job_name: 'performance-metrics'
        static_configs:
          - targets: ['localhost:8001']  # Performance monitor metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: cloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: config
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: cloud-storage
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30003
  selector:
    app: prometheus 