apiVersion: batch/v1
kind: Job
metadata:
  name: sensu-init
  namespace: cloud-storage
spec:
  template:
    spec:
      containers:
      - name: sensuctl
        image: sensu/sensu:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          sensuctl configure --non-interactive --url http://sensu-backend-service:8080 --username admin --password P@ssw0rd! &&
          sensuctl namespace create cloud-storage
      restartPolicy: Never
  backoffLimit: 4 