apiVersion: v1
kind: ConfigMap
metadata:
  name: sensu-checks-config
  namespace: cloud-storage
data:
  checks.json: |
    {
      "type": "CheckConfig",
      "api_version": "core/v2",
      "metadata": {
        "name": "node-health",
        "namespace": "cloud-storage"
      },
      "spec": {
        "command": "/etc/sensu/plugins/check-node-health.py",
        "handlers": [],
        "interval": 60,
        "publish": true,
        "subscriptions": ["system"],
        "timeout": 30,
        "runtime_assets": []
      }
    }
  pod-health.json: |
    {
      "type": "CheckConfig",
      "api_version": "core/v2",
      "metadata": {
        "name": "pod-health",
        "namespace": "cloud-storage"
      },
      "spec": {
        "command": "/etc/sensu/plugins/check-pod-health.py",
        "handlers": [],
        "interval": 30,
        "publish": true,
        "subscriptions": ["system"],
        "timeout": 30,
        "runtime_assets": []
      }
    }
  metrics.json: |
    {
      "type": "CheckConfig",
      "api_version": "core/v2",
      "metadata": {
        "name": "system-metrics",
        "namespace": "cloud-storage"
      },
      "spec": {
        "command": "/etc/sensu/plugins/metrics-system.py",
        "handlers": [],
        "interval": 15,
        "publish": true,
        "subscriptions": ["system"],
        "timeout": 30,
        "runtime_assets": [],
        "output_metric_format": "nagios_perfdata"
      }
    } 