apiVersion: v1
kind: ServiceAccount
metadata:
  name: sensu-agent
  namespace: cloud-storage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sensu-agent
rules:
- apiGroups: [""]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sensu-agent
subjects:
- kind: ServiceAccount
  name: sensu-agent
  namespace: cloud-storage
roleRef:
  kind: ClusterRole
  name: sensu-agent
  apiGroup: rbac.authorization.k8s.io 