apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensu-backend
  namespace: cloud-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensu-backend
  template:
    metadata:
      labels:
        app: sensu-backend
    spec:
      containers:
      - name: sensu-backend
        image: sensu/sensu:latest
        command: ["/bin/sh"]
        args:
        - -c
        - |
          # Install curl
          apk add --no-cache curl

          # Start backend
          sensu-backend start &
          sleep 10
          sh /etc/sensu/bootstrap/init.sh
          wait
        ports:
        - containerPort: 8080
          name: api
        - containerPort: 8081
          name: agent
        - containerPort: 3000
          name: dashboard
        volumeMounts:
        - name: bootstrap
          mountPath: /etc/sensu/bootstrap
        - name: checks
          mountPath: /etc/sensu/checks
      volumes:
      - name: bootstrap
        configMap:
          name: sensu-backend-bootstrap
          defaultMode: 0755
      - name: checks
        configMap:
          name: sensu-checks-config 