apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sensu-agent
  namespace: cloud-storage
  labels:
    app: sensu-agent
    role: monitoring
spec:
  selector:
    matchLabels:
      app: sensu-agent
  template:
    metadata:
      labels:
        app: sensu-agent
        role: monitoring
    spec:
      serviceAccountName: sensu-agent
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 0
      containers:
      - name: sensu-agent
        image: sensu/sensu:latest
        command: ["sensu-agent"]
        args:
        - "start"
        - "--log-level=debug"
        - "--backend-url=ws://sensu-backend-service:8081"
        - "--name=$(NODE_NAME)"
        - "--namespace=cloud-storage"
        - "--subscriptions=system"
        - "--deregister=true"
        - "--keepalive-interval=5"
        - "--keepalive-timeout=15"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PYTHONPATH
          value: "/etc/sensu/plugins/lib"
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "sensu-agent version"
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "sensu-agent version"
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: plugins
          mountPath: /etc/sensu/plugins
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
      initContainers:
      - name: install-plugins
        image: python:3.9-alpine
        command: ["/bin/sh"]
        args:
        - -exc
        - |
          # Install build dependencies
          apk add --no-cache gcc musl-dev linux-headers

          # Create directories
          mkdir -p /plugins/lib /plugins/scripts
          
          # Debug
          echo "Current directory:"
          pwd
          echo "ConfigMap contents:"
          ls -la /configmap
          
          # Copy scripts
          cp -v /configmap/* /plugins/scripts/
          chmod +x /plugins/scripts/*.py
          
          # Install Python packages
          pip install --no-cache-dir --target=/plugins/lib psutil
          pip install --no-cache-dir --target=/plugins/lib kubernetes
          
          # Verify installation
          echo "Installed packages:"
          pip list
          echo "Scripts directory:"
          ls -la /plugins/scripts
        volumeMounts:
        - name: plugins
          mountPath: /plugins
        - name: plugin-scripts
          mountPath: /configmap
      volumes:
      - name: plugins
        emptyDir: {}
      - name: plugin-scripts
        configMap:
          name: sensu-plugins
          defaultMode: 0755
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys 