apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
  namespace: cloud-storage
data:
  sshd_config: |
    Port 22
    PermitRootLogin no
    PasswordAuthentication no
    PubkeyAuthentication yes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssh-access
  namespace: cloud-storage
spec:
  selector:
    matchLabels:
      app: ssh-access
  template:
    metadata:
      labels:
        app: ssh-access
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - worker
                - master
      containers:
      - name: ssh-container
        image: alpine:latest
        command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
      volumes:
      - name: ssh-config
        configMap:
          name: ssh-config 