apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  sshd_config: |
    Port 22
    PermitRootLogin no
    PasswordAuthentication no
    PubkeyAuthentication yes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssh-access
spec:
  selector:
    matchLabels:
      app: ssh-access
  template:
    metadata:
      labels:
        app: ssh-access
    spec:
      containers:
      - name: ssh-server
        image: linuxserver/openssh-server
        ports:
        - containerPort: 22
        volumeMounts:
        - name: ssh-config
          mountPath: /etc/ssh/sshd_config
          subPath: sshd_config
      volumes:
      - name: ssh-config
        configMap:
          name: ssh-config 