apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: monitoring
spec:
  replicas: 5
  selector:
    matchLabels:
      role: worker
  template:
    metadata:
      labels:
        role: worker
    spec:
      containers:
      - name: worker
        image: ubuntu:latest
        command: ["/bin/sh", "-c", "sleep infinity"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: worker-storage
          mountPath: /storage
      volumes:
      - name: worker-storage
        emptyDir: {} 